name: Test connexion Azure

on:
  push:
    branches: ["main"]

jobs:
  test-connexion:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Connexion à Azure
      - name: Connexion à Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Vérifier la connexion
      - name: Vérifier abonnement Azure
        run: az account show
